version: '3.8'

services:
  backend:
    container_name: node-test
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
